const customerData = [
  {
    id: 1,
    firstname: "Ajay",
    lastname: "Raj",
    mail: "ajay@example.com",
    phonenumber: " 9159209658",
    address: "Rspuram",
    city: "Coimbatore",
    state: "Tamilnadu",
    country: "India",
    postalcode: "641018",
  },
  {
    id: 2,
    firstname: "Barath",
    lastname: "Kumar",
    mail: "barath@example.com",
    phonenumber: " 9159209659",
    address: "Anna Salai",
    city: "Chennai",
    state: "Tamilnadu",
    country: "India",
    postalcode: "600002",
  },
  {
    id: 3,
    firstname: "Cris",
    lastname: "Sam",
    mail: "cris@example.com",
    phonenumber: " 9159209679",
    address: "Velachery",
    city: "Chennai",
    state: "Tamilnadu",
    country: "India",
    postalcode: "600012",
  },
  {
    id: 4,
    firstname: "Dhanush",
    lastname: "Jogi",
    mail: "dhanush@example.com",
    phonenumber: " 9159209636",
    address: "ATC",
    city: "Ooty",
    state: "Tamilnadu",
    country: "India",
    postalcode: "643103",
  },
  {
    id: 5,
    firstname: "Fathima",
    lastname: "Mohamed",
    mail: "fathima@example.com",
    phonenumber: " 9159209655",
    address: "Gandhi Nagar",
    city: "Salem",
    state: "Tamilnadu",
    country: "India",
    postalcode: "636001",
  },
  {
    id: 6,
    firstname: "Harish",
    lastname: "Krishna",
    mail: "harish@example.com",
    phonenumber: " 9159209699",
    address: "Kotagiri",
    city: "Coonoor",
    state: "Tamilnadu",
    country: "India",
    postalcode: "643018",
  },
  {
    id: 7,
    firstname: "Jon",
    lastname: "Adam",
    mail: "jon@example.com",
    phonenumber: " 9159209699",
    address: "Anna Nagar",
    city: "Madurai",
    state: "Tamilnadu",
    country: "India",
    postalcode: "625001",
  },
  {
    id: 8,
    firstname: "Mohan",
    lastname: "Krishna",
    mail: "mohan@example.com",
    phonenumber: " 9159209699",
    address: "Rajaji street",
    city: "Dindigul",
    state: "Tamilnadu",
    country: "India",
    postalcode: "624001",
  },
  {
    id: 9,
    firstname: "Oviya",
    lastname: "Ramkumar",
    mail: "oviya@example.com",
    phonenumber: " 9159209699",
    address: "Nehru coloney",
    city: "karur",
    state: "Tamilnadu",
    country: "India",
    postalcode: "639001",
  },
  {
    id: 10,
    firstname: "Priya",
    lastname: "Mohan",
    mail: "priya@example.com",
    phonenumber: " 9159209699",
    address: "Chithra Nagar",
    city: "Kanyakumari",
    state: "Tamilnadu",
    country: "India",
    postalcode: "629702",
  },
];

export { customerData };
